#!/bin/sh

echo 'Mounting filesystems...'
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

echo 'Running depmod...'
depmod -ae

echo 'Setting up mdev...'
echo /sbin/mdev > /proc/sys/kernel/hotplug
modprobe uhci-hcd
/sbin/mdev -s

CONSOLE_LEVEL=15
echo "Set console log level to ${CONSOLE_LEVEL}... "
echo $CONSOLE_LEVEL > /proc/sys/kernel/printk
